services:
  - type: web
    name: telegram-shop-admin
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestBuildsFromRoot: true
    envVars:
      - key: NODE_VERSION
        value: 24.14.1
